# Generated by Django 4.1 on 2024-01-03 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FBAInventoryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalSKU', models.PositiveIntegerField(default=0)),
                ('totalBoxes', models.PositiveIntegerField(default=0)),
                ('nameOnInventory', models.CharField(max_length=255)),
                ('companyName', models.CharField(max_length=255)),
                ('packageComingFrom', models.TextField(help_text='Amazon eBay Walmart')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='orders/')),
                ('comments', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('requested', 'Requested'), ('acknowledged', 'Acknowledged'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('trackingNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('receivedStatus', models.CharField(choices=[('inventoryReceived', 'Inventory Received'), ('notReceivedYet', 'Not Received yet')], default='notReceivedYet', max_length=20)),
                ('logisticsComments', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'FBA Inventory Requests',
            },
        ),
        migrations.CreateModel(
            name='FBMInventoryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalSKU', models.PositiveIntegerField(default=0)),
                ('totalBoxes', models.PositiveIntegerField(default=0)),
                ('nameOnInventory', models.CharField(max_length=255)),
                ('companyName', models.CharField(max_length=255)),
                ('packageComingFrom', models.TextField(help_text='Amazon eBay Walmart')),
                ('comments', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('requested', 'Requested'), ('acknowledged', 'Acknowledged'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('trackingNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('receivedStatus', models.CharField(choices=[('inventoryReceived', 'Inventory Received'), ('notReceivedYet', 'Not Received yet')], default='notReceivedYet', max_length=20)),
                ('logisticsComments', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'FBM Inventory Requests',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20, null=True)),
                ('products', models.TextField(default='[]')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='orders/')),
                ('total', models.PositiveBigIntegerField(default=0)),
                ('comments', models.TextField(blank=True, default='', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Invoices',
            },
        ),
        migrations.CreateModel(
            name='LogisticsRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('businessName', models.CharField(max_length=255)),
                ('businessAddress', models.CharField(max_length=500)),
                ('status', models.CharField(blank=True, choices=[('reject', 'Reject'), ('approve', 'Approve')], default='', max_length=20, null=True)),
                ('branch', models.CharField(choices=[('fba', 'FBA'), ('fbm', 'FBM')], default='fba', max_length=3)),
                ('type', models.CharField(blank=True, choices=[('oa', 'OA'), ('wholesale', 'Wholesale')], default='', max_length=9, null=True)),
                ('minimumInventory', models.CharField(blank=True, choices=[('0-30', '0-30'), ('50-100', '50-100'), ('100<', '100<')], default='0-30', max_length=8, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Logistic Registrations',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labelType', models.CharField(choices=[('labelYourself', 'Label Yourself'), ('provideLabel', 'Provide Label')], default='labelYourself', max_length=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('requested', 'Requested'), ('acknowledged', 'Acknowledged'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('trackingNumber', models.TextField(blank=True)),
                ('pdf', models.FileField(upload_to='orders/')),
                ('prep', models.TextField(blank=True)),
                ('expectedDeliveryDate', models.DateField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'FBM Orders',
            },
        ),
        migrations.CreateModel(
            name='Warehouses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('isGlobal', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Warehouses',
            },
        ),
    ]
