# Generated by Django 4.1 on 2023-12-31 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('isGlobal', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FBAInventoryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalSKU', models.PositiveIntegerField(default=0)),
                ('totalBoxes', models.PositiveIntegerField(default=0)),
                ('nameOnInventory', models.CharField(max_length=255)),
                ('companyName', models.CharField(max_length=255)),
                ('packageComingFrom', models.TextField(help_text='Amazon eBay Walmart')),
                ('comments', models.TextField()),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('accepted', 'Accepted'), ('cancelled', 'Cancelled'), ('declined', 'Declined'), ('error', 'Error')], default='requested', max_length=20)),
                ('trackingNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('receivedStatus', models.CharField(choices=[('inventoryReceived', 'Inventory Received'), ('notReceivedYet', 'Not Received yet')], default='notReceivedYet', max_length=20)),
                ('logisticsComments', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.warehouses')),
            ],
        ),
    ]
