# Generated by Django 4.1 on 2023-12-31 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogisticsRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('businessName', models.CharField(max_length=255)),
                ('businessAddress', models.CharField(max_length=500)),
                ('branch', models.CharField(choices=[('fba', 'FBA'), ('fbm', 'FBM')], default='fba', max_length=3)),
                ('type', models.CharField(choices=[('oa', 'OA'), ('wholesale', 'Wholesale')], default='oa', max_length=9)),
                ('minimumInventory', models.CharField(choices=[('0-30', '0-30'), ('50-100', '50-100'), ('100<', '100<')], default='0-30', max_length=8)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
