# Generated by Django 4.1 on 2024-01-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logisticsregistration',
            name='minimumInventory',
            field=models.CharField(blank=True, choices=[('0-30', '0-30'), ('50-100', '50-100'), ('100<', '100<')], default='0-30', max_length=8, null=True),
        ),
    ]
