# Generated by Django 4.1 on 2024-01-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_logisticsregistration_minimuminventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='logisticsregistration',
            name='status',
            field=models.CharField(blank=True, choices=[('reject', 'Reject'), ('approve', 'Approve')], default='', max_length=20, null=True),
        ),
    ]
